baseURL = "https://example.com/"
languageCode = "en-US"
title = "Ed Almusalamy"
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "img/profile.jpg"
  author = "Ed Almusalamy"
  description = "Describe your website"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "EdA271"
  Email         = "edalmusalamy@gmail.com"
  LinkedIn      = "ed-almusalamy-049174220"

## Main Menu
[[menu.main]]
  name = "About Me"
  weight = 100
  identifier = "aboutme"
  url = "/aboutme/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
